const items = {
    rebirth: [
        {id: 1, name: 'The Sad Onion'},
        {id: 2, name: 'The Inner Eye'},
        {id: 3, name: 'Spoon Bender'},
        {id: 4, name: 'Cricket’s Head'},
        {id: 5, name: 'My Reflection'},
        {id: 6, name: 'Number One'},
        {id: 7, name: 'Blood of the Martyr'},
        {id: 8, name: 'Brother Bobby'},
        {id: 9, name: 'Skatole'},
        {id: 10, name: 'Halo of Flies'},
        {id: 11, name: '1UP'},
        {id: 12, name: 'Magic Mushroom'},
        {id: 13, name: 'The Virus'},
        {id: 14, name: 'Roid Rage'},
        {id: 15, name: '<3'},
        {id: 16, name: 'Raw Liver'},
        {id: 17, name: 'Skeleton Key'},
        {id: 18, name: 'A Dollar'},
        {id: 19, name: 'Boom!'},
        {id: 20, name: 'Transcendence'},
        {id: 21, name: 'The Compass'},
        {id: 22, name: 'Lunch'},
        {id: 23, name: 'Dinner'},
        {id: 24, name: 'Dessert'},
        {id: 25, name: 'Breakfast'},
        {id: 26, name: 'Rotten Meat'},
        {id: 27, name: 'Wooden Spoon'},
        {id: 28, name: 'The Belt'},
        {id: 29, name: 'Mom’s Underwear'},
        {id: 30, name: 'Mom’s Heels'},
        {id: 31, name: 'Mom’s Lipstick'},
        {id: 32, name: 'Wire Coat Hanger'},
        {id: 33, name: 'The Bible'},
        {id: 34, name: 'The Book of Belial'},
        {id: 35, name: 'The Necronomicon'},
        {id: 36, name: 'The Poop'},
        {id: 37, name: 'Mr. Boom'},
        {id: 38, name: 'Tammy’s Head'},
        {id: 39, name: 'Mom’s Bra'},
        {id: 40, name: 'Kamikaze!'},
        {id: 41, name: 'Mom’s Pad'},
        {id: 42, name: 'Bob’s Rotten Head'},
        {id: 43, name: 'Teleport!'},
        {id: 44, name: 'Yum Heart'}, 
        {id: 45, name: 'Lucky Foot'},
        {id: 46, name: 'Doctor’s Remote'},
        {id: 47, name: 'Cupid’s Arrow'},
        {id: 48, name: 'Shoop Da Whoop!'},
        {id: 49, name: 'Steven'},
        {id: 50, name: 'Pentagram'},
        {id: 51, name: 'Dr. Fetus'},
        {id: 52, name: 'Magneto'},
        {id: 53, name: 'Treasure Map'},
        {id: 54, name: 'Mom’s Eye'},
        {id: 55, name: 'Lemon Mishap'},
        {id: 56, name: 'Distant Admiration'},
        {id: 57, name: 'Book of Shadows'},
        {id: 58, name: 'The Ladder'},
        {id: 59, name: 'Charm of the Vampire'},
        {id: 60, name: 'The Battery'},
        {id: 61, name: 'Steam Sale'},
        {id: 62, name: 'Anarchist Cookbook'},
        {id: 63, name: 'The Hourglass'},
        {id: 64, name: 'Sister Maggy'},
        {id: 65, name: 'Technology'},
        {id: 66, name: 'Chocolate Milk'},
        {id: 67, name: 'Growth Hormones'},
        {id: 68, name: 'Mini Mush'},
        {id: 69, name: 'Rosary'},
        {id: 70, name: 'Cube of Meat'},
        {id: 71, name: 'A Quarter'},
        {id: 72, name: 'PhD'},
        {id: 73, name: 'X-Ray Vision'},
        {id: 74, name: 'My Little Unicorn'},
        {id: 75, name: 'Book of Revelations'},
        {id: 76, name: 'The Mark'},
        {id: 77, name: 'The Pact'},
        {id: 78, name: 'Dead Cat'},
        {id: 79, name: 'Lord of the Pit'},
        {id: 80, name: 'The Nail'},
        {id: 81, name: 'We Need to Go Deeper!'},
        {id: 82, name: 'Deck of Cards'},
        {id: 83, name: 'Monstro’s Tooth'},
        {id: 84, name: 'Loki’s Horns'},
        {id: 85, name: 'Little Chubby'},
        {id: 86, name: 'Spider Bite'},
        {id: 87, name: 'The Small Rock'},
        {id: 88, name: 'Spelunker Hat'},
        {id: 89, name: 'Super Bandage'},
        {id: 90, name: 'The Gamekid'},
        {id: 91, name: 'Sack of Pennies'},
        {id: 92, name: 'Robo-Baby'},
        {id: 93, name: 'Little C.H.A.D.'},
        {id: 94, name: 'The Book of Sin'},
        {id: 95, name: 'The Relic'},
        {id: 96, name: 'Little Gish'},
        {id: 97, name: 'Little Steven'},
        {id: 98, name: 'The Halo'},
        {id: 99, name: 'Mom’s Bottle of Pills'},
        {id: 100, name: 'The Common Cold'},
        /*
        {id: 101},
        {id: 102},
        {id: 103},
        {id: 104},
        {id: 105},
        {id: 106},
        {id: 107},
        {id: 108},
        {id: 109},
        {id: 110},
        {id: 111},
        {id: 112},
        {id: 113},
        {id: 114},
        {id: 115},
        {id: 116},
        {id: 117},
        {id: 118},
        {id: 119},
        {id: 120},
        {id: 121},
        {id: 122},
        {id: 123},
        {id: 124},
        {id: 125},
        {id: 126},
        {id: 127},
        {id: 128},
        {id: 129},
        {id: 130},
        {id: 131},
        {id: 132},
        {id: 133},
        {id: 134},
        {id: 135},
        {id: 136},
        {id: 137},
        {id: 138},
        {id: 139},
        {id: 140},
        {id: 141},
        {id: 142},
        {id: 143},
        {id: 144},
        {id: 145},
        {id: 146},
        {id: 147},
        {id: 148},
        {id: 149},
        {id: 150},
        */
    ],
};

export default items;